const express = require('express')
const app = express()
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.set("view engine", "ejs")
app.use(express.static(path.join(___dirname, 'public')))
app.get("/", function (req, res) {
    res.render("index")
})
app.listen(3000)
// const path = require('path')
// console.log(path.join(__dirname, "public"))